### PR TITLE
Video field enhancements

### PR DESCRIPTION
**Pull request by Lyquix**
Simplified fetch mechanism to use only embed.ly API. We don't have to worry about maintaining 4 different integrations, but has the following consequences:
1. In order for the field to work you must have an embed.ly API key, which you can get for free
2. We no longer have access to the video duration information, so it has been removed entirely
3. Forcing SSL and autostart are options that are generated at the time of fetch (saved in the embed URL). Changing them requires re-fetching of all stored videos.

Updated edit form to use updated styles
Updated display to work better with responsive styles

### CODE REVIEW

**Comment by micker** [comment]
yes but we need to add message about this because fetching doesn't work if we didn't have api key

**Comment by ggppdk** [comment]
This is nice work !

about error message 
- i was adding error message to all 4 apis, that show warning if free views have finished

i will merge my changes for error messaging with yours

**Comment by ggppdk** [comment]
I have updated the APIs in shareaudio.php
- support for youtube v3 API and new parameter for API key
- added error reporting (all 4 APIs) for both error via HTTP header or via JSON server responce
- added parameter for disabling native APIs: youtube, vimeo, dailymotion and using only embed.ly
- in field configuration API parameters are in seperate TAB so that user will configure it more easily

will update sharevideo field with same changes

**Comment by Lyquix** [comment]
Would you agree with the following modifications for both sharedaudio and sharedvideo:

1. add warning message in item form when there is no embed.ly key
2. show alert to user when embed.ly key limit has been exceeded or an error ocurred
3. use only embed.ly API (eliminate youtube, dailymotion and vimeo)
4. when interacting with API verify that the response is actually a video/audio, issue message for user if entered URL doesn't contain video/audio
5. add multi-value

**Comment by Lyquix** [comment]
Another question about process: I have been using branches and pull request to send code for you to review. It is not always final and ready for merging with the master branch. Is that okay or do you want me to follow a different process for just showing you code and getting your feedback?

**Pull request merged**
