### PR TITLE
Cleanup code tabulation and formatting

### PR DESCRIPTION
**Pull request by Lyquix**

### CODE REVIEW

**Comment by ggppdk** [comment]
Let's not merge this, please wait to pull my changes first

**Comment by Lyquix** [comment]
Ok

**Comment by ggppdk** [comment]
@Lyquix 
I have commited, please overwrite / reset changes you have on addressint field
using:
```
git fetch
git checkout origin/master .\plugins\flexicontent_fields\addressint\*
```
i say overwrite so that you also get the many code formating change that i made
then you may test and add anything else you wish

- then please update your pull request with the changes to the code formating and the minor bug fixes i made, or close it, thanks

**Comment by ggppdk** [comment]
@Lyquix 
a question, will you submit more changes to 'addressint' field in the near future ?
if you do i will avoid doing any work on it
- e.g. working on multi-value and field group support, which anyway will not be in v3.0.9

**Comment by Lyquix** [comment]
If you give me some guidance or example on how to setup multi value and group support I can work on that.

**Pull request closed without merging**
