### PR TITLE
Further enhancements to sharedvideo:

### PR DESCRIPTION
**Pull request by Lyquix**
1. Update onBeforeSave to use new data structure
1. Handles errors: missing api key, error when communicating with api, and URL not a video
2. Shows nice error messages using class alert-warning
3. Collapses form when no video has been fetched
4. Added capability for multiple values and usage in groups
5. Added pre-text, post-text, open tag, closing tag, and separator functionality

### CODE REVIEW

**Comment by Lyquix** [comment]
Guys, please review and test. I think the work is done, but please take a close look. I have never worked before with multi-values and groups, so I am not 100% I covered everything correctly.

Once this is finished, I suggest porting to sharedaudio (it is basically the same plugin but for audio).

I will soon have a surprise for you: in addition to the office hours field that we are working on (it works already we are just polishing it), we are starting development on a "multimedia gallery" field that will be a combination of the image, video and audio fields. It will allow you to create a gallery, and when viewing in lightbox it will load the video/audio player for the items that are video or audio (like photos in Facebook)

**Comment by ggppdk** [comment]
About embed.ly, it allows free views, this changes behaviour by requiring user to immediately add the API key in configuration

- surely this is better than the field suddenly stop working without message (in item form)
but we could make this to be warning / info message instead of forcing it, 
- also in shareaudio i added error reporting of server response we can do both the above:
 an information message and the error reporting for server response

about the old JS code, i would not want to delete we can leave it inside the field commented or make it optional (as done in shareaudio.php) (see new configuration), now we rely only on embed.ly

**Comment by ggppdk** [comment]
hhmm, i am wrong,
 embed.ly requires key for free views,
 i was confused because i forgot i had API key in the configuration

**Comment by ggppdk** [comment]
This is great work, it works !

Some small fixes needed (i will commit soon)
Field viewing
- when field belongs to a fieldgroup you need to add empty html to the array if field has no value in the group:
```
if (...empty check) {}
  if ($use_ingroup) $field->{$prop}[$n] = '';
  continue;
}
```

Item Form:
- the multi-value JS code use count($field->value), but you intialized it when empty after the JS code, thus next item number starts with 0 instead of 1, i moved it above
- the JS unique row variable is 'uniqueRowNum' and not 'rowCount', the later increments but also decrements when you click delete thus you will get duplicate ids and duplicate fieldnames, i changed it
- great idea to use regular expression for replacing FORM Element names and HTML Tag IDs, 
you used:
```
var newField_HTML = lastField.prop('outerHTML');
...
```
then you made string replacement, i made a small addition:
```
var newField = jQuery(newField_HTML );
```
so that JS code is similar / consistent with other fields, also i had made a recent change in adding new elements to the DOM related to a minor bug-fix, and wanted to keep the insertion method the same

**Comment by ggppdk** [comment]
I have commited the fixes

**Comment by ggppdk** [comment]
After we test changes for sharevideo and shareaudio we can release v3.0.9 rc7, which i hope  it will be our v3.0.9. 
About porting changes to shareaudio will do in v3.1.0
Purpose is to have a robust v3.0.9 which will be long lived with minor bug fixes and shift work to v3.1.0

**Comment by Lyquix** [comment]
Thank you! Did you see how I handle adding new values in JS? I take the initial form as an HTML string, and use regex to update IDs and form names:

```
var lastField = fieldval_box ? fieldval_box : jQuery(el).prev().children().last();
var newField = lastField.prop('outerHTML');
newField = newField.replace(/" . str_replace(array('[', ']'), array('\[', '\]'), $fieldname) . "\[(\d*)\]/g, '" . $fieldname . "[' + rowCount" . $field->id . " + ']');
newField = newField.replace(/" . $elementid . "_(\d*)/g, '" . $elementid . "_' + rowCount" . $field->id . ");
newField = newField.replace(/data-row=\"(\d*)\"/g, 'data-row=\"' + rowCount" . $field->id . " + '\"');
```

Let me know if that approach is good. It works, but I wasn't sure if would dislike the "shortcut" I took :-)

**Comment by micker** [comment]
i add new option : size per video and corrected general video size (for video field)

**Pull request merged**
