### PR TITLE
Update default.php

### PR DESCRIPTION
**Pull request by iamrobert**
Remove FLEXI_J16GE & FLEXI_J30GE calls

### CODE REVIEW

**Comment by ggppdk** [comment]
You are right to remove these
a reason to leave them there was to be easier to find places that will use e.g. this
```php
var $btn_sm_class  = FLEXI_J40GE ? 'btn btn-sm' : 'btn btn-small';
```
(we did the above in other views)
but it is really easy to find them any way so i will just go ahead and merge this

**Comment by ggppdk** [comment]
Thanks

**Comment by iamrobert** [comment]
I am currently upgrading our admin template - so that's why I noticed it.

Also, have updated flexiContent icons in SVG as well as png:

https://we.tl/t-OoLSjSYyJn

Let me know if you want the .ai file to change colours etc.

**Comment by ggppdk** [comment]
Please note that the some replacements of FLEXI_J16GE were wrong 

e.g.
$ctrl = FLEXI_J16GE ? 'items.' : '';
should have been made $ctrl = 'items.';

i have made a commit just now to correct them, please pull the correction commit to you local copy )) ...

about icons you can make a new PR, especially for png you should only need to just add the new updated files to the PR ?

**Comment by ggppdk** [comment]
About icons , thinking to distribute our own subset of font-awesome pack (free or a purchased version) that will be have own CSS class prefix to avoid conflicts, 
This should be performance wise and also responsive like SVG ?

**Comment by iamrobert** [comment]
An icon font can work - but you are stuck with 1 colour design, and some of those icons are complex. That's why I did it as svg, and you may need multiple colours to differentiate the design. 

If you want to go with a font icon - I usually use:
+ http://fontastic.me/

**Pull request merged**
