### PR TITLE
Update en-GB.com_flexicontent.ini

### PR DESCRIPTION
**Pull request by iamrobert**
The language string for association in 
index.php?option=com_flexicontent&view=category&layout=edit&id=54&extension=com_flexicontent
is missing
not sure if you are renaming it to FLEXI_SELECT_CAT

### CODE REVIEW

**Comment by ggppdk** [comment]
Yes,

let this be open for a while, you may find a few more strings, and add more to it

**Comment by iamrobert** [comment]
download

**Comment by iamrobert** [comment]
FLEXI_CAN_ADD_CUSTOM_FIELD_COLUMNS_COMPONENT_AND_PER_TYPE

**Comment by ggppdk** [comment]
A yes that string no longer exists in neither frontend / backend file, i will remove it

(we have added instructions here:)

itemsman_instructions

**Comment by iamrobert** [comment]
IS 
FLEXI_FORM_IS_BEING_SUBMITTED="Form is being submitted ..." still being used?

**Comment by ggppdk** [comment]
form_is_being_submitted

**Comment by iamrobert** [comment]
In Universal Module:
FLEXI_ORDER_HIGHEST_ITEM_ID="ID -- Highest First"
FLEXI_ORDER_LOWEST_ITEM_ID="ID -- Lowest First"
FLEXI_ORDER_CONFIGURED_ORDER="Ordering in current category"
FLEXI_PLEASE_SELECT="Please Select"

**Comment by ggppdk** [comment]
Ok, i think the best, is to load the backend component language when editing FLEXIcontent modules, and remove ALL common language strings from FLEXIcontent modules (strings used for configuration)

**Comment by iamrobert** [comment]
FLEXI_YES="YES"
FLEXI_NO="NO"

Micker uses for his admin module

**Comment by ggppdk** [comment]
Fixed the missing language strings, closing this PR

**Pull request closed without merging**
