### PR TITLE
Lyquix addressint enhancements

### PR DESCRIPTION
**Pull request by Lyquix**
Several enhancements to the addressint field, as referred from #43 and #92 

**Overview:** the areas of improvements can be summarized as: 1) integration with Google Maps Places API for easy editing of addresses, 2) streamline editing form with several configuration options for customizing the forms according to needs, and 3) use of interactive map in the frontend, and ability to completely customize the display

### Field Configuration

**Editing**

* Update xml to take advantage of new FC styles and depend_class functionaly
* Address edit mode: you can configure the field to provide a textarea field or a form with the address components (street, city, state, etc.).
* Option to show/hide address component fields: addr2, addr3, state, province, zip suffix and country
* Because of the use of Google Maps Places autocomplete functionality there is no need set default or unique countries or states
* Option to allow latitude and longitude to be edited

**API Keys**

Added fields for entering Google Maps API keys. One for Javascript API, and the other for static maps API. The label description includes URLs for getting such keys. This is optional but recommended to avoid hitting usage limits.

**Viewing**

* Show address: never, category view only, item view only, both
* Address display mode: use the simple textarea display or use a formatted mode where the address components (street, city, state, etc.) are included in an address format
* Address format: allows to substitute with address values, as well as create conditional areas based on whether a specific component exists or not.
* Control directions link - don't display, place before or after address
* Customize directions link text
* Show map: never, category view only, item view only, both
* Embed type: keep image embed for backward compatibility, added new interactive map mode
* Zoom levels is now default zoom level because it can be changed on each item. Added labels for reference of how zoomed in or out each level is.

### Data

In addition to the existing address components, new components have been added when saving the field:

* **addr_display:** plain text field that stores how the address will be displayed when using the plain text display mode
* **addr_formatted:** stores the plan text address as provided originally by Google Maps
* **zip_suffix:** stores the suffix or extended value for zip/postal codes
* **url:** stores the Google Maps URL for getting directions, as provided by the Google Maps API
* **zoom:** stores the zoom level customized for the item

### Item Form

* New "Search address" field integrated with Google Maps Places API allows for very easy finding of addresses and preventing mispellings
* No need to click a Geolocate button. The process is done automatically when an address is selected.
* Depending on the setting for address edit mode the user will see a single "Display address" field or a form with the various address components
* If allowed the latitu
* Preview using interactive map. When zoom level is changed, the new value is saved and used in frontend

### Frontend Display

* Use of interactive map
* Address displayed using format template

### TO DO:

* Multiple values
* Default CSS styles for interactive map: I didn't want to mess with CSS, but here is what you need to know to make the map fully responsive in the frontend:

The following classes will make the map responsive with a 16:9 proportion:

```css
.map_canvas {
    width: 100%;
    height: 0;
    padding-bottom: 56.25%;
}
```

Ideally you also need to trigger a Javascript function that re-initializes the map or re-centers it as the window resizes.

### CODE REVIEW

**Comment by ggppdk** [comment]
Merged, will test changes

**Comment by ggppdk** [comment]
Just a note,
project files use leading tabs instead of spaces
(i will include a change for this in next commits)

you should set your editor to use leading tabs, and also better set spaces for each tab to 2

**Comment by Lyquix** [comment]
Looks like my editor got misconfigured, I will fix this.

**Comment by micker** [comment]
whoooo great great enchanced !
did you an idea for display an summary map in categorie view ?

**Comment by ggppdk** [comment]
@Lyquix 

Please wait before making any other changes to addressint field,
- your contribution is great, just you used an older version of the files, and you removed some minor things, like:
 "silently enforcing single country"
 (country becomes hidden and gets specific value)

i will restore these and you can pull changes back, and do further changes / confirm my changes

**Comment by Lyquix** [comment]
I did that on purpose. Since now we are using autocomplete functionality, there doesn't seem to be a need for a default country. My understanding is that having a default country was useful because scrolling the long list of countries was very time-consuming if you have to do it many times.

**Comment by ggppdk** [comment]
Adding that back should not break your changes, 
the single country was not because of selecting from long list but 
- to make it simpler
- also -enforce- single country

so i believe it is quite useful for people only needing 1 country, or the above needs are covered by your changes ?

**Comment by Lyquix** [comment]
I believe it is no longer needed. Test it and let me know. 

With autocomplete the country is always filled in, and we have more complete location data, even if it is not displayed. If the admin decides to display country later, values don't need to be updated.

**Comment by ggppdk** [comment]
I see will let single country option inside be inside comments until we are sure

Minor things (besides code formating leading spaces), that i found fixed:
- some unset configuration (PHP) variables, (if you enable PHP error reporting you will see them)
- zip_suffix uses wrong form name 'province' inside onBeforeSaveField
- we enforce form disabled/unused fields (address2, province, etc) inside onBeforSaveField so that user does not save them manually (they will not be displayed but they will be added to DB data), so just better enforce them

**Comment by ggppdk** [comment]
Also question does "autocomplete" field need to be saved in DB ?
it is only needed inside item form, right ?

**Comment by Lyquix** [comment]
Thank you Georgio
I think autocomplete doesn't need to be saved to db

**Comment by ggppdk** [comment]
I have commited, please overwrite any reset changes you have on addressint field
using:
```
git fetch
git checkout origin/master .\plugins\flexicontent_fields\addressint\*
```
i say overwrite so that you also get the many code formating change that i made
then you may test and add anything else you wish

**Comment by ggppdk** [comment]
Also i did not remove the force single country, if you think it is an issue then disable / remove it

**Comment by ggppdk** [comment]
I have added some CSS to the 2 containers of
- address data and
- map

to make a map container responsive:
with this commit: 41757f7
```
/* FIELDs: (addessint field) */
.fcfield_addressint_data {
	float:left; min-width:380px; width:unset; max-width:unset; padding:0; margin:0; box-sizing:border-box;
}
.fcfield_addressint_map {
	float:left; min-width:50%;   width:unset; max-width:unset; padding:0; margin:0; box-sizing:border-box;
}

@media only screen and (min-width: 1671px) {
	.fcfield_addressint_data { min-width:380px; }
	.fcfield_addressint_map  { min-width:70%; }
}
@media only screen and (min-width: 1270px) and (max-width: 1670px) {
	.fcfield_addressint_data { min-width:380px; }
	.fcfield_addressint_map  { min-width:60%; }
}
@media only screen and (min-width: 1020px) and (max-width: 1269px)  {
	.fcfield_addressint_data { min-width:380px; }
	.fcfield_addressint_map  { min-width:50%; }
}

@media only screen and (max-width: 1019px) {
	.fcfield_addressint_data { min-width:100%; }
	.fcfield_addressint_map  { min-width:100%; }
}
```

**Pull request merged**
