### PR TITLE
Remove "btn-group" from non-radio parameters in mod_flexicontent.xml

### PR DESCRIPTION
**Pull request by iamrobert**
I believe there is a bug as you can't write in textarea with " btn-group btn-group-yesno"

### CODE REVIEW

**Comment by ggppdk** [comment]
You pull request is based on outdated (older) version of the module, also can you tell what are you fixing / improving ?

**Comment by iamrobert** [comment]
Sorry - I was using the FLEXIcontent master version:
https://github.com/FLEXIcontent/flexicontent-cck/blob/master/modules/mod_flexicontent/mod_flexicontent.xml

I am building a client template to simplify FLEXIcontent Administration for my clients. Here's my older version of FLEXIcontent administrator template: https://github.com/iamrobert/flexi

So, now I am updating to FLEXI3 - and simplifying the code base from last time - and trying to implement twitter bootstrap - so it more closely follows the existing ISIS template. Code:

```
<div class="control-group">
        <div class="control-label">
          <label> Title </label>
        </div>
                <div class="controls">
                    <input></div>
      </div>
```

Its also helping me improve my php & coding skills.

Before I launch the new version via github - I was creating a site first to see if there are any issues and encountered this bug - but realized its been addresses in a newer version.

If you wanna see it - please let me know.

Screenshots:
Item:
download 1

Item Manager:
item-manager

**Comment by ggppdk** [comment]
i see,

- i think you can override 
administrator/component/com_flexicontent/views/item/tmpl/default.php
administrator/templates/TEMPLATENAME/html/com_flexicontent/item/default.php

but to let this be more flexible, we can do this:
- we can have more backend form templates

views/item/tmpl/default.php
views/item/tmpl/default_simple1.php
views/item/tmpl/default_simple2.php
views/item/tmpl/default_car.php
views/item/tmpl/default_hotel.php

- and in "type" configuration we can allow selecting a different template
or load by default this:
views/item/tmpl/default_typealias.php

**Comment by iamrobert** [comment]
That would work - and would be immensely powerful - especially for the item manager.

The other idea I had was utilizing a form validation wizard:
(http://vadimg.com/twitter-bootstrap-wizard-example/examples/basic-formvalidation.html#) - so when a user needs to create a new article - it forces them to fill in the correct category/language etc. I guess it could also skip a lot of the options - like template options.

The main problems clients have are:
a) forgetting to set the language
b) forgetting to add items to the menu
c) working out how to translate

The other problem is every client wants to be a "Super Administrator" - they don't want someone to control their website. Its difficult because clients want their CMS to be like FB - super simple and easy. So - I think hiding buttons is the best solution.

This is a good overview:
http://magazine.joomla.org/issues/issue-feb-2012/item/667-Customizing-an-Extensions-Edit-Screen

**Comment by ggppdk** [comment]
I will include removal of btn-group from textarea in next commit, so i am closing this

**Pull request closed without merging**
