### PR TITLE
Update default.php

### PR DESCRIPTION
**Pull request by iamrobert**
Cleaner on mobile?

Its more similar to Joomla default category - and hides certain categories on mobile and tablet.

### CODE REVIEW

**Comment by ggppdk** [comment]
This is ok , as long as you added same CSS classes hidden-phone hidden-tablet , to header columns too
will review / test this and merge it

**Comment by ggppdk** [comment]
Ok it looks like hidden cells in header row are a proper match for the corresponding columns,
merged

**Comment by iamrobert** [comment]
Thanks - but I don't see it in the master:
https://github.com/FLEXIcontent/flexicontent-cck/blob/master/admin/views/items/tmpl/default.php

**Comment by ggppdk** [comment]
your above link is pointing to 'items' manager contibuted for categories manager
.../views/categories/tmpl/default.php

**Pull request merged**
