### PR TITLE
Preparing for the Json and XML views for Mobile Apps Integrations

### PR DESCRIPTION
**Pull request by Igcorreia**
For now we need to try to put together 2 views: Json and XML put primarily JSON.
- In the Json view we need to get the category public data and the print it as JSON.
- work in progress...
-In category view put ?format=xml or format=json
Note: need help here

### CODE REVIEW

**Comment by Lyquix** [comment]
Ignacio, take a look at this post:

http://www.flexicontent.org/forum/index.php?f=30&t=6562&rb_v=viewtopic

and this:

https://github.com/Lyquix/flexicontent_templates

I implemented as templates,  but you may use the code for implementing is as views.

**Comment by Igcorreia** [comment]
That is where I copied from and also I had old code I used for an Mobile App integration.
It should be in the view, in my point of view, because that way we respect the category configuration, and if the menu overrides it we will respect it to. The same happens to the item view. But I am no expert in views, I need FC help. I found a way to get it working with all views, not it needs to be implemented as a core feature :)

**Comment by Lyquix** [comment]
I agree this should be its own view.

**Comment by ggppdk** [comment]
Hello, thanks you both,
As there were some conflicts, i have merged this manually here: a512044

Closing this pull request

**Pull request closed without merging**
