### PR TITLE
Dashboard Update

### PR DESCRIPTION
**Pull request by iamrobert**
FLEXIcontent Dashboard Update:

Screen

### CODE REVIEW

**Comment by iamrobert** [comment]
ok

**Comment by micker** [comment]
Very cool that compatible with joomla 3 ?

**Comment by iamrobert** [comment]
Possibly.

Joomla 3 has reached its EOL (17 August 2023).

If Joomla's not supporting J3 - I'm unsure why FLEXIcontent still is.


**My Plan:**
I plan to build the admin backend like this rather than combine it with the component files in the site folder:

@import url('1_flexi_form.less');
@import url('2_flexi_containers.less');
@import url('3_flexi_shared.less');
@import url('flexi_backend.less');

that way I can more easily integrate it into a new admin template.

I'm only planning to update the:

1. dashboard
2. item
3. items 

I'll share with you when done - but not sure how to integrate with the main codebase.

ITEM:

**Comment by micker** [comment]
For we need to check j3 compatibility. This dashboard looks great
For item concept we want to display form liké joomla4 form for core sorry)
But you Can create your owb item view

**Pull request closed without merging**
