### PR TITLE
Add support for aliases in the WHERE clause, when using depend on master field feature (valgrp property)

### PR DESCRIPTION
**Pull request by prathumwan**
Running into an MySQL error because its not allowed to use an alias in a WHERE clause. The workaround is to use the expression that was used in the SELECT part of the query.

Changed using the sql expression from the value group SELECT expression to build the WHERE clause. Maybe put that scan for the expression in a function or use other code if you have in your framework. The '_valgrp_in_' substitute is not needed anymore, but sequence must be value,text,valgrp or value,text,image,valgrp.

Test recording with gadm.org data put on vimeo (https://vimeo.com/174007364)

### CODE REVIEW

**Comment by ggppdk** [comment]
Will use this or will provide an alternative, in any case will allow such usage

**Comment by prathumwan** [comment]
Yes Georgios, use this or similar. I just start learning with php, joomla,
and your framework, but think you can see what it should do.

Btw, great work to put the field elements in a edit form, easy to use!

Is there is a way to hide the cascaded levels that are locked, showing them
step by step only if there is a choice availible? What you think?

2016-07-12 0:39 GMT+07:00 Georgios Papadakis <notifications@github.com>:

**Comment by JeBy777** [comment]
Is this going to be added to the master? It solved some cascading problems I was having using SQL Query 👍

**Comment by ggppdk** [comment]
Yes will test for v3.1.1 version and add it if no problems,
it has such a milestone,

**Comment by ggppdk** [comment]
Thanks, I have added this PR manually with commit: 719b956

**Comment by ggppdk** [comment]
@prathumwan 
So this is now included in v3.1.0:
https://github.com/FLEXIcontent/flexicontent-cck/releases

Please re-test, i will test it a little more too

**Comment by prathumwan** [comment]
Thanks Georgios.

My first testing was not successful, because i had removed the _VALGRP_IN_
substitute constant in my settings.

I changed the syntax by adding the _VALGRP_IN_ constant to the end:
    "select value as value,text as text,image as image,valgrp as valgrp
from #__table where condition _VALGRP_IN_"
Using that syntax it works fine. Also if no where condition is used
("....from #__table _VALGRP_IN_").

If _VALGRP_IN_ is used before a where condition:
    "select value as value,text as text,image as image,valgrp as valgrp
from #__table where _VALGRP_IN_ and condition"
It is not working, because you get a query like ".... from #__table where
AND valgrp IN ('xxx') and condition"

I can live with that, but think the more user-friendly solution is to don't
use that substitute constant at all. If concatenate "$query .= $and_clause"
 unconditionally (\classes\flexicontent.fields.php starting line 1694-1696)
it puts value group related content allways to the end of the query string.
What you think?


2016-10-08 19:44 GMT+07:00 Georgios Papadakis <notifications@github.com>:

**Comment by ggppdk** [comment]
The query may have other SQL clauses, like "HAVING" clause or "GROUP BY" or "ORDER BY", thus the "WHERE" clause may not be the last clause
- thus appending the AND clause of "value group" limitations, to the query may not work in all cases.

So it is best to keep there replacement "_VALGRP_IN_", to allow administrator, to place it at the 

Also i am testing an improvement locally for having the SELECT columns: value, text, image, valgrp in any order. Will commit soon

**Comment by prathumwan** [comment]
You're right, I had not considered that.

**Comment by ggppdk** [comment]
@prathumwan 
Thanks for feedback / testing,

I have commited final code, with improvement for having the SELECT columns: value, text, image, valgrp in any order. You may install final code and confirm it is working

Some more comment. I thought of using "HAVING" clause thus we can just use the column alias,
- but as you already know, this is slow in large tables, as it will cause the full table(s) to retrieved due to WHERE clause being empty, and then HAVING clause will filter the rows

Usual case is to have "TA.col_name_1 as valgrp",
and we just want to catch "TA.col_name_1" and use it in WHERE
- so will not use HAVING in any case, to avoid encourage / rely on using slow queries

Even thought of adding a parameter in which administrator can write the "TA.col_name_1", this will remove the need to parse the query, but wanted to avoid 1 more parameter, that may cause confusion

**Comment by prathumwan** [comment]
OK, will test it. 
I agree not using HAVING because of the slow performance with bigger record sets (and time is adding up using multiple cascading levels). Usage is predestined for the kind of data from countries, states, regions, etc., which always have lots of records.

**Comment by prathumwan** [comment]
I don't get it working, you see something wrong in my queries?

image


as text:
1st `$query=select iso_id0 as value, name as text, concat(iso,'.png') as image from #__administratives where lvl=0`
2nd `$query=select concat(iso_id0,'-',iso_id1) as value,concat(type,' ',name) as text,type as image,iso_id0 as valgrp from #__administratives where _valgrp_in_ and lvl=1`
3rd `$query=select concat(iso_id0,'-',iso_id1,'-',iso_id2) as value,concat(type,' ',name) as text,concat(iso_id0,'-',iso_id1) as valgrp from #__administratives where _valgrp_in_ and lvl=2`
4th `$query=select concat(iso_id0,'-',iso_id1,'-',iso_id2,'-',iso_id3) as value,concat(type,' ',name) as text,concat(iso_id0,'-',iso_id1,'-',iso_id2) as valgrp from #__administratives where _valgrp_in_ and lvl=3`

**Comment by ggppdk** [comment]
Ok thanks,
 i ll test with these queries maybe it seems my regexp splitting is breaking

**Comment by prathumwan** [comment]
yes, that's what i thought, may be its caused by building the field names.
attached is my test table.

[administratives.zip](https://github.com/FLEXIcontent/flexicontent-cck/files/518357/administratives.zip)

**Comment by ggppdk** [comment]
Code was working but wrong method was called:
```
Array
(
    [value] => concat(iso_id0,'-',iso_id1) 
    [text] => concat(type,' ',name) 
    [image] => type 
    [valgrp] => iso_id0 
)
Array
(
    [value] => concat(iso_id0,'-',iso_id1,'-',iso_id2) 
    [text] => concat(type,' ',name) 
    [valgrp] => concat(iso_id0,'-',iso_id1) 
)
Array
(
    [value] => concat(iso_id0,'-',iso_id1,'-',iso_id2,'-',iso_id3) 
    [text] => concat(type,' ',name) 
    [valgrp] => concat(iso_id0,'-',iso_id1,'-',iso_id2) 
)
```

Should be good now, fixed with: https://github.com/FLEXIcontent/flexicontent-cck/commit/9954180781f37d9ce547dc1e871a8e935b06b6a5

**Comment by prathumwan** [comment]
There is something more at the select.php (and similar):

This check for the array element always failed `if ( isset($element_cols[$valgrp]) )` I realized $valgrp was not defined, so tought its a typo and tried this `if ( isset($element_cols['valgrp']) )` and that did'nt work too.

I tested this `if ( array_key_exists('valgrp', $element_cols))` and this it worked! but don't know why the `isset` is not.

Finally just added `$valgrp = 'valgrp';` because `isset()` is much faster then `array_key_exists()`

image

**Comment by ggppdk** [comment]
Ok thanks for testing,
I fixed the non-set variable
https://github.com/FLEXIcontent/flexicontent-cck/commit/d29c3bae3bf6b55b56158dad0c78b1f44f494e95

If you will email me the 4 tables used by the fields, together with queries, it will help for future updates

I think we can release v3.1.0 now, anything else will go to later release

**Comment by prathumwan** [comment]
Thanks, it works well now!

I don't understand why this `isset($element_cols['valgrp']) ` using a constant was not working. Has the value within the brackets [] to be a variable, or depends it from used PHP version?

For reasonable testing you need also graphics, language files, etc.
I'll test a bit more and give you a complete backup after some clean up.

**Pull request closed without merging**
