### PR TITLE
Applying Joomla Coding Standards

### PR DESCRIPTION
**Pull request by acs-ferreira**
This is a first PR of a series if this one is accepted.
Feedback welcomed. 👍

### CODE REVIEW

**Comment by ggppdk** [comment]
Wanted to do this and we have been making this changes on every oportunity of a new feature or even during bug fixing

but e.g.
the extra spaces inside parenthesis are everywhere and they need to be removed
similar the required spaces at string concatenations need to be added

so there are a lot of places that need updating

A question did you do this manually
or did you a tool (which one ?) and then did some manual work too

**Comment by acs-ferreira** [comment]
Yes, both auto and manual.
For the auto part: https://github.com/joomla/coding-standards/

The main question is: will this be merged and are you interested in these PRs?

**Comment by ggppdk** [comment]
Because the changes need to be reviewed before being merged

this is the way i would like to do it

1. i would like to use same tool as you to apply most of changes to my local copy
2. then i will use a comparison tool to review the remaning manual work that you have done

**Comment by acs-ferreira** [comment]
No problem, just use the Git repo then.
Instructions inside! 👍

**Comment by ggppdk** [comment]
I have just now reviewed appsman.php (5 minutes work) (and will review the rest tomorrow)
it is good

just i noticed only that statement
return;
when inside a switch statement is not indented properly, it gets zero padded

**Comment by acs-ferreira** [comment]
Yes, didn't saw that one.
But let me know if you'll do a try on you local repo or if i should submit new PRs.

**Pull request merged**
