### PR TITLE
Update items default.php

### PR DESCRIPTION
**Pull request by iamrobert**
Hi,

1. I have added col_ratings etc to the table header (th). If someone wants to permanently hide tags or ratings or votes etc - as the site doesn't use them - it makes it simpler to hide. 
2. have added class small for some of the table items which will work better for smaller screens and is more inline with Joomla.
3. I would also recommend changing the "icon-checkmark" back to "icon-menu" for Change State - as when clients see the icon they might think publish rather than unpublish.

<span title="Change State" class="icon-checkmark"></span>

### CODE REVIEW

**Comment by ggppdk** [comment]
The version of the file that you updated is a little old

Recently we added code to 
- hide columns (user-hidden columns) via server-side PHP login, and thus avoid JS on page load which shows all columns and the hides them, and this causes slow rendering (several seconds if you try to show 200 or 500 items per page) plus you get a jumping effect

you code has undone the above changes, you need to update your local copy of master branch and redo your PR

**Comment by iamrobert** [comment]
Thanks - does this work:

https://github.com/iamrobert/flexicontent-cck/pull/1

**Comment by ggppdk** [comment]
Hi , will you update this PR ? or you want to do a new one ?

**Comment by iamrobert** [comment]
Have reposted

**Pull request closed without merging**
