### PR TITLE
Update field_InlineBoxes.php

### PR DESCRIPTION
**Pull request by iamrobert**
I believe this allows us to upload image files correctly if its in a tab or wherever.

I believe it resolves this issue:

https://github.com/FLEXIcontent/flexicontent-cck/issues/1199

### CODE REVIEW

**Comment by micker** [comment]
hello @iamrobert can you test last master this issue is solved

**Comment by micker** [comment]
hello @iamrobert can you test last master this issue is solved

**Comment by micker** [comment]
@iamrobert i merge can you confirm that is ok after update ?

**Comment by iamrobert** [comment]
Yes - it works I can upload and save but I realized there was the:

btn fcfont-icon icon icon-pencil fas fa-info-circle image-option which was
looking for values - so perhaps better to do it like this:
https://github.com/FLEXIcontent/flexicontent-cck/pull/1217

**Pull request merged**
