### PR TITLE
Multiple XSS vulnerabilities in backend views

### PR DESCRIPTION
**Pull request by WiReD-**
It is possible to inject javascript code in some text search fields and it's also possible to add javascript at element names like tags or types.
stored-xss

### CODE REVIEW

**Comment by ggppdk** [comment]
will test and merge this soon

**Comment by WiReD-** [comment]
I added missing htmlspecialchars

**Comment by micker** [comment]
Thanks for help8ng

**Comment by ggppdk** [comment]
Merged

**Pull request merged**
