### PR TITLE
Save filter values and options for use in custom templates

### PR DESCRIPTION
**Pull request by rubenreyes2000**
The purpose of this commit is to save the filter value, and its options as part of $this -> filters, so that the data can be used in custom templates that need to recreate filters.

### CODE REVIEW

**Comment by ggppdk** [comment]
In 3.3.x , we are using layouts which already include the $results inside their $displayData
see below
i have backported the layouts to 3.2.x branch, you can create your custom overrides: and in them check fieldnames or field ids, this is neater than adding your custom filter code inside our category template layout

/templates/TEMPLATENAME/html/layouts/com_flexicontent/items_list_filters/select_selectmul.php
/templates/TEMPLATENAME/html/layouts/com_flexicontent/items_list_filters/radio_checkbox.php
/templates/TEMPLATENAME/html/layouts/com_flexicontent/items_list_filters//txtsearch_date_slider.php

```php
$displayData = array(
	'filter' => & $filter,
	'filter_ffid' => $filter_ffid,
	'filter_ffname' => $filter_ffname,
	'results' => & $results,
	'value' => $value,
	'require_all_values' => $require_all_values,
	'isSearchView' => $isSearchView,
);

$layouts_path = $app->isSite() ? null : JPATH_SITE.DS.'components'.DS.'com_flexicontent'.DS.'layouts';
...

/**
 * Create the form field(s) used for filtering, note output is captured into filter->html,
 * but we do 'echo JLayoutHelper::render()' for debugging
 * Place override at: /templates/TEMPLATENAME/html/layouts/com_flexicontent/items_list_filters/
 */
switch ($display_filter_as)
{
	// 0: Select (single value selectable), 2: Dual select (value range), 6: Multi Select (multiple values selectable)
	case 0: case 2: case 6:
		echo JLayoutHelper::render(
			'items_list_filters.select_selectmul',
			$displayData,
			$layouts_path
		);
		break;
...

**Comment by ggppdk** [comment]
Here are the files to customize
https://github.com/FLEXIcontent/flexicontent-cck/tree/master/site/layouts/items_list_filters

duplicating them as

/templates/TEMPLATENAME/html/layouts/com_flexicontent/items_list_filters/select_selectmul.php
/templates/TEMPLATENAME/html/layouts/com_flexicontent/items_list_filters/radio_checkbox.php
/templates/TEMPLATENAME/html/layouts/com_flexicontent/items_list_filters//txtsearch_date_slider.php

**Comment by rubenreyes2000** [comment]
Georgios - would you consider adding my code in the individual layouts? 

With your current changes I'd need to develop these overrides in order to have access to the filter data in my FLEXIcontent templates. It seems quite convoluted when it can be added to the $this->filters object.

I will make a new PR for your review.

**Comment by ggppdk** [comment]
there is a small to moderate memory penalty and a small CPU penalty on passing results like this
when in 99% of the websites the $results will not be used ...

you see after creation of every filter in its layout
the $results becomes stale and immediately or on-garbage collection its memory is freed

if you add a reference to $result to every filter,
a page with many filters will also have all results arrays maintained in memory until they reach the category layout

I suggest that you do this
create overrides that only
1. "include" the default (**thus you will avoid maintaining a duplicated code of them**) 
2. set $filter->results according to your needs

Also **if you are not going to use the default code** of the filter layouts
and instead you want to create a custom display
- then you --want-- to create overrides that will not run any code at all , i mean avoid executing the default filtering HTML creation of default layouts, that will go wasted **and slow down your page !!**

**Comment by rubenreyes2000** [comment]
Those are very good points.
Thank you!

**Comment by ggppdk** [comment]
In your overrides you can decide or not to use the default filtering HTML 
by checking

$field->field_type 
- to effect **all fields of a field type**

$field->id (or $field->name) 
- to effect **a specific field(s)**

and then do your custom HTML 
- either inside the layout override 
- or do it inside category*.php of your template by using $filter->results ... of 1 or more filters

**Pull request closed without merging**
