### PR TITLE
Fix for https://github.com/FLEXIcontent/flexicontent-cck/issues/969 multiselect sortable field bug

### PR DESCRIPTION
**Pull request by rubenreyes2000**
This code properly handles the values order for a multiselect sortable field with saved values.
Bug is caused because the default values is always loaded, and ignores the order already saved by user.

### CODE REVIEW

**Comment by micker** [comment]
@ggppdk  ?

**Comment by ggppdk** [comment]
This used to work, i will check why this is broken now

**Comment by rubenreyes2000** [comment]
You were not able to reproduce the error? Did you see the description in https://github.com/FLEXIcontent/flexicontent-cck/issues/969?

**Comment by rubenreyes2000** [comment]
You can see the bug in action in this video, on a fresh installation:
https://www.loom.com/share/aa9353679d444e07bc3cc1e2ab6b7068
you can skip to 1:39 to see the field settings and the watch the error happening after the last item save

**Comment by ggppdk** [comment]
Sorry, I closed this PR by mistake

**Comment by ggppdk** [comment]
The PR was closed, because i deleted the branch, but i can still see your suggested fix, will review this soon

**Comment by ggppdk** [comment]
Re-ordering the options before load has some advantages , with only disadvantage changing default order, which may not be bad

Just , i have reviewed this
and i could not replicate it
i have configured to have default values but i still see the values i have re-ordered after form reloads

Still because we want to replace select2 (as we can not use select2 JS v4 because it is too SLOW !!!!)
This maybe useful
Still i wonder why this is failing. Do you have an online testing website that shows this is issue, can you send me login to such a -testing- website via email ?

**Comment by micker** [comment]
Yep maybe its time to check choice.js because it Will be added to joomla 4

**Comment by ggppdk** [comment]
Yes, i have done some evaluation of it
and i have mentioned it before somewhere that it seems to be our best option for replacement is choice.js

**Comment by rubenreyes2000** [comment]
@ggppdk did you follow all the steps listed in https://github.com/FLEXIcontent/flexicontent-cck/issues/969 to reproduce the error?

**Comment by ggppdk** [comment]
Thanks,
i have tested your suggested fix and committed it

**Pull request closed without merging**
